### PR TITLE
Use media group for bazarr

### PR DESCRIPTION
**Pull request by tbaumann**
Bazarr had no write access to the media library

### CODE REVIEW

**Comment by rasmus-kirk** [comment]
https://github.com/rasmus-kirk/nixarr/blob/a3fad60dd2f5110536eb13f24e7529b2506ade6d/nixarr/bazarr/default.nix#L90

Bazarr is in the media group though

**Comment by tbaumann** [comment]
That doesn't mean anything if the files aren't written with the same GID AFAIK. The effective group id is bazarr and the owner is different.

Anyway, it works if I change it. And it's consistent with the rest of the services

**Comment by tbaumann** [comment]
No I was wrong. Forget it. The umask for sonarr is also wrong. Group has only read access

**Comment by tbaumann** [comment]
`-rw-r--r-- 1 sonarr media ...`

**Comment by tbaumann** [comment]
The umask was my fault. (Set in tramsmission)

But I'm almost certain that this PR is still useful. But let's put it on hold until I confirm

**Comment by tbaumann** [comment]
Hm, :raised_eyebrow: Indeed  all is good if the file  permissions are right.

**Comment by rasmus-kirk** [comment]
You should be able to run `sudo fix-permissions` to fix any permission mismatches you may have caused.

**Pull request closed without merging**
